// NOTE: Do not edit this file. It is built by running `./scripts/create-static-site-files.js`
// NOTE: Generated at 2019-05-13T20:11:32.725Z
import ExamplePage from './example-page';
import PageIndex from './page-index';

export default [
  {
    component: ExamplePage,
    group: 'Eksempelgruppe',
    name: 'Eksempelside',
    path: '/eksempelside'
  },
  {
    component: PageIndex,
    group: 'Ungrouped',
    name: 'Page Index',
    path: '/'
  }
];
