// NOTE: Do not edit this file. It is built by running `./scripts/create-static-site-files.js`
// NOTE: Generated at 2019-05-16T16:50:37.417Z
import ExamplePage from './example-page';
import PageIndex from './page-index';
import Test from './test';

export default [
  {
    component: ExamplePage,
    group: 'Eksempelgruppe',
    name: 'Eksempelside',
    path: '/eksempelside'
  },
  {
    component: PageIndex,
    group: 'Ungrouped',
    name: 'Page Index',
    path: '/'
  },
  {
    component: Test,
    group: 'Ungrouped',
    name: 'test',
    path: '/test'
  }
];
