// NOTE: Do not edit this file. It is built by running `./scripts/create-static-site-files.js`
// NOTE: Generated at 2019-05-21T16:14:03.948Z
module.exports = ['/article-page', '/eksempelside', '/', '/test'];
