// NOTE: Do not edit this file. It is built by running `./scripts/create-static-site-files.js`
// NOTE: Generated at 2019-08-19T12:52:20.471Z
module.exports = ['/article-page', '/eksempelside', '/', '/test'];
